-- Generated by brand_rebuild.ps1
-- Brand verify: 吼堂

SELECT b.name AS brand_name, COUNT(*) AS cnt
FROM materials m
LEFT JOIN brands b ON b.id = m.restaurant_brand_id
WHERE b.name = '吼堂'
GROUP BY b.name;

SELECT COUNT(DISTINCT m.category) AS category_cnt
FROM materials m
JOIN brands b ON b.id = m.restaurant_brand_id
WHERE b.name = '吼堂';

SELECT
  COUNT(*) AS total,
  COUNT(NULLIF(TRIM(COALESCE(m.pic_folder, '')), '')) AS has_pic_folder,
  COUNT(NULLIF(TRIM(COALESCE(m.image, '')), '')) AS has_image
FROM materials m
JOIN brands b ON b.id = m.restaurant_brand_id
WHERE b.name = '吼堂';

SELECT m.code, COUNT(*) AS dup_n
FROM materials m
JOIN brands b ON b.id = m.restaurant_brand_id
WHERE b.name = '吼堂'
GROUP BY m.code
HAVING COUNT(*) > 1;
