#!/usr/bin/env python3
"""
根据 materials_cleaned.csv 生成 PostgreSQL，为 materials 表写入 pic_folder 与完整 OSS image URL，
与 renli2026 桶下 materials/<品牌目录>/<短目录>/<code>.png 一致（品牌目录可选）。

使用前在 DMS 执行（若尚无列）:
  ALTER TABLE materials ADD COLUMN IF NOT EXISTS pic_folder TEXT;

用法:
  python sql_update_materials_pic_folder_image.py
  python sql_update_materials_pic_folder_image.py -o ../../sql/materials_pic_image_update.sql
  python sql_update_materials_pic_folder_image.py --brand-folder xiaolongkan --brand-name 小龙坎
"""
from __future__ import annotations

import argparse
from pathlib import Path
from urllib.parse import quote

import pandas as pd

OSS_BASE = "https://renli2026.oss-cn-chengdu.aliyuncs.com/materials"


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    ap = argparse.ArgumentParser()
    ap.add_argument("-i", "--input", type=Path, default=root / "materials_cleaned.csv")
    ap.add_argument("-o", "--output", type=Path, default=root / "sql" / "materials_pic_image_update.sql")
    ap.add_argument("--brand-folder", default="", help="OSS 品牌目录，例如 xiaolongkan")
    ap.add_argument("--brand-name", default="", help="若提供，则 UPDATE 仅作用于该品牌名")
    args = ap.parse_args()

    df = pd.read_csv(args.input, dtype=str, keep_default_na=False)
    df.columns = [str(c).strip().lower() for c in df.columns]

    lines: list[str] = [
        "-- Generated by sql_update_materials_pic_folder_image.py",
        "-- ALTER TABLE materials ADD COLUMN IF NOT EXISTS pic_folder TEXT;",
        "BEGIN;",
    ]

    for _, row in df.iterrows():
        code = str(row.get("code", "")).strip()
        pic = str(row.get("pic_folder", "")).strip()
        if not code or not pic:
            continue
        fn = str(row.get("image_filename", "")).strip()
        ext = Path(fn).suffix.lower() if fn else ".png"
        if ext not in (".png", ".jpg", ".jpeg", ".webp", ".gif"):
            ext = ".png"
        file_part = f"{code}{ext}"
        # 与前端 encodeURIComponent(目录) 一致
        if args.brand_folder.strip():
            url = f"{OSS_BASE}/{quote(args.brand_folder.strip(), safe='')}/{quote(pic, safe='')}/{quote(file_part, safe='')}"
        else:
            url = f"{OSS_BASE}/{quote(pic, safe='')}/{quote(file_part, safe='')}"

        where_clause = f"WHERE m.code = {sql_str(code)}"
        if args.brand_name.strip():
            where_clause += (
                " AND m.restaurant_brand_id = ("
                f"SELECT id FROM brands WHERE name = {sql_str(args.brand_name.strip())} LIMIT 1)"
            )

        lines.append(
            f"UPDATE materials m SET pic_folder = {sql_str(pic)}, image = {sql_str(url)} "
            f"{where_clause};"
        )

    lines.append("COMMIT;")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(df)} rows -> {args.output.resolve()}")


if __name__ == "__main__":
    main()
